
version: 2

sources:
  - name: raw
    schema: reboot_1999
    tables:
      - name: customers
        identifier: raw_customers1
      - name: items
        identifier: raw_items1
      - name: orders
        identifier: raw_orders1
      - name: products
        identifier: raw_products1
      - name: stores
        identifier: raw_stores1
      - name: supplies
        identifier: raw_supplies1